Add game win and game over prevent focus on button
Matt-Warnock/space_invaders pull request #14
Opened 2020-05-28 16:50 UTC by Matt-Warnock

I'm thinking, it might be time to make a seperate gameLogic class.
what do you think?

2020-05-28 23:54 UTC, octopusinvitro requested changes
For some reason the blur is not working for me :thinking: 

![spaceinvaders](https://user-images.githubusercontent.com/2157089/83198942-26d5ae80-a138-11ea-90d9-7144fb9af62f.gif)


Regarding a separate gameLogic class, I think I would rather extract the operations on the screen out of the game, so that you have a class that is responsible for encapsulating all the knowledge about the screen, how to manipulate it, how to draw things on it, etc. Then, the game can just use it.

2020-05-28 23:54 UTC, octopusinvitro commented on game.js
> -    this.gameIsRunning = false;
Now that I think about it, since you are passing the game to the player already, you don't need to pass the game size to the player, the player can ask the game for its size. :+1:

2020-05-28 23:54 UTC, octopusinvitro commented on game.js
> +    this.screen.clearRect(0, 0, this.gameSize.x, this.gameSize.y);
You do not need to call `clearRect()` here, `run()` already calls the `draw()` method, which starts with this same line.

2020-05-28 23:54 UTC, octopusinvitro commented on game.js
> +      this.checkStatus();
you don't need to pass `this.screen` and `this.gameSize` to the draw method. You can just call them from inside the draw method.

2020-05-28 23:54 UTC, octopusinvitro commented on game.js
> +        this.gameInitialized = true;
This won't actually stop the game from running, `requestAnimationFrame` will keep running the `tick()` function forever and you won't have any control over that. Since you have the `this.gameInitialized` flag, you can turn it on and off in relevant moments in the game. Think of when you implement lives, you will want to have a better control of it as well.

To be in full control of the game, I would recommend setting the flag off when you have a win or a loose, and only run the tick function if the flag is on.

```js
    // when the start button is pressed, set the flag to true, meaning the game starts
    button.addEventListener('click', () => {
      this.gameInitialized = true;
      this.gameReset();
      this.run();
    });

  // when there is a win or a game over, set it to false, meaning the game stops
  checkStatus() {
    if (this.haveBeenDestroyed('Player')) {
      this.textGameMiddle('Game Over');
      this.gameInitialized = false;

    } else if (this.haveBeenDestroyed('Invader')) {
      this.textGameMiddle('You Win!');
      this.gameInitialized = false;
    }
  }

  // Only run the tick function on a loop while the game hasn't been stopped
  run() {
    let tick = () => {
      this.update();
      this.draw();
      this.checkStatus();

      if (this.gameInitialized) {
        requestAnimationFrame(tick);
      }
    };

    tick();
  }
```

2020-05-28 23:54 UTC, octopusinvitro commented on game.js
> +    } else if (this.haveBeenDestroyed('Invader') && !this.haveBeenDestroyed('Player')) {
You don't need to check for `!this.haveBeenDestroyed('Player')`.
You are on the `else` branch of an `if` that checks for `this.haveBeenDestroyed('Player')`.
So if you made it to the else branch is because the player was not destroyed.

This is enough:
```js
if (this.haveBeenDestroyed('Player')) {
  // bla bla
} else if (this.haveBeenDestroyed('Invader')) {
  // bla bla
}

2020-05-29 10:49 UTC, Matt-Warnock commented on game.js
> +    this.screen.clearRect(0, 0, this.gameSize.x, this.gameSize.y);
if I were to do that, it would trigger reqestAnimationFrames again.

2020-05-29 10:50 UTC, Matt-Warnock commented on game.js
> -    this.gameIsRunning = false;
ah, cool!

2020-05-29 10:53 UTC, Matt-Warnock commented on game.js
> +      this.checkStatus();
good point. this and other refactoring from origial code I left as was/am still unsure if I'll refactor some of this methods to a diffrent class

2020-05-29 10:53 UTC, octopusinvitro commented on game.js
> +    this.screen.clearRect(0, 0, this.gameSize.x, this.gameSize.y);
What I mean is that you can delete this line.

```js
gameReset() {
    this.bodies = this.createInvaders().concat(new Player(this, this.gameSize));
  }
```

2020-05-29 11:02 UTC, Matt-Warnock commented on game.js
> +        this.gameInitialized = true;
Ah, you mean, as I did in my previous comitt. This is more of a question of design choise (I will contact you about that). 

However, the tick() running when the user is not engaged with the page is very concerning and I intend to add a listener to stop the tick() running to prevent the potentiol of running in the background.

I have thought about player lives. I think it is an advatage to have the tick() running when a player dies and respwans, the button resets the game and there for the players lives.

2020-05-29 11:03 UTC, Matt-Warnock commented on game.js
> +    } else if (this.haveBeenDestroyed('Invader') && !this.haveBeenDestroyed('Player')) {
ah cool!

2020-05-29 11:36 UTC, Matt-Warnock commented on game.js
> +    this.screen.clearRect(0, 0, this.gameSize.x, this.gameSize.y);
I was Just about to delete my comment in the hope that you haddnt read it yet.
I have instead, got around gameReset() being fired in that condition, its only needed in that instance to populate the boddies array. so I've now set the property value back to were it was so on first call the boodies are populated.

2020-05-29 11:42 UTC, Matt-Warnock commented on game.js
> +    this.screen.clearRect(0, 0, this.gameSize.x, this.gameSize.y);
I will get rid of clearRect as requested.

2020-05-29 15:22 UTC, octopusinvitro commented on game.js
> +    this.bodies = this.bodies = this.createInvaders().concat(new Player(this));
Beware typo:

```
    this.bodies = this.bodies = this.createInvaders().concat(new Player(this));
```

You have `this.bodies = ` twice.

Also, to avoid repetition, you could call `gameReset()` here, so that you don't have to update the code to create the bodies in two places.:


```js
  // ...
  this.gameLeftSide = 0;
  this.gameReset();
  this.userEngaged = false;
```

2020-05-29 15:22 UTC, octopusinvitro commented on game.js
> +    window.addEventListener('blur', () => this.userEngaged = false);
this event listener would make more sense if you moved it to the initialize method

```js
  initialize() {
    button.addEventListener('focus', event => event.currentTarget.blur());
    window.addEventListener('blur', () => this.userEngaged = false);
    // ...
  }

run() {
    let tick = () => {
      this.update();
      this.draw(this.screen, this.gameSize);
      this.checkStatus();

      if (this.userEngaged) {
        requestAnimationFrame(tick);
      }
    };
    tick();
  }
```

2020-05-29 15:27 UTC, octopusinvitro commented on game.js
> +      this.checkStatus();
[YAGNI](https://martinfowler.com/bliki/Yagni.html)

You don't know yet what that class looks like, or if this method is even going to be there.
I would say, clean it now, and adapt the code when and if you need to.

2020-05-29 16:20 UTC, merged